### ISSUE TITLE
[Bug] Slowmode Ring around Logo

### ISSUE THREAD

**Issue by ScarVite** [SevenTV/SevenTV#188] opened 2021-12-02 16:56 UTC
**Describe the bug**
When using 7tv on Youtube on a Channel in Slowmode, the "Loading" ring is around the 7tv logo instead of the send button

**To Reproduce**
1. go to a Youtube livestreams, with slowmode enabled
2. send a message
3. Observe the "next Message available loader"

**Expected behavior**
The loading ring should appear around the send button not the 7tv logo

**Screenshots**
![firefox_VyMXSTlspl](https://user-images.githubusercontent.com/43887376/144466976-f391a0da-b411-429e-b768-2c43fff9c140.png)

**Version:**
2.0.2

**Comment by robmonte** [comment] 2021-12-03 04:13
Duplicate of https://github.com/SevenTV/SevenTV/issues/153

**Comment by Cryptizism** [comment] 2022-02-20 14:14
#189 solves this issue
@AnatoleAM can you close this issue?

**Closed** 2022-02-20 14:15 UTC
Labels: bug
