### ISSUE TITLE
[Bug] Replies not working

### ISSUE THREAD

**Issue by zetta** [SevenTV/SevenTV#246] opened 2022-04-18 04:40 UTC
**Describe the bug**
When the extension is enabled replying to a message sends the message as normal message

**To Reproduce**
1. Go to any twitch channel
2. Click on reply icon in any mesasge
3. See your message as normal message instead of reply

**Expected behavior**
The message should be shown as a reply in twitch chat

**Screenshots**
Typing a message in reply box
![image](https://user-images.githubusercontent.com/204105/163755286-c5446002-8bc5-46fb-bd51-936d0da56ef9.png)

After sending, the message appears as normal message (without even mention the user)
![image](https://user-images.githubusercontent.com/204105/163755300-ac16fe55-397b-4abc-b62b-03602796b8c7.png)

This is after disabling the extension
![image](https://user-images.githubusercontent.com/204105/163755395-f375f4c1-008f-41a9-91cd-75c76442ffd1.png)

**Version:**
The version where the bug is occuring (e.g 2.2.0)

**Comment by AnatoleAM** [comment] 2022-04-18 04:46
Duplicate of #243

**Closed by AnatoleAM** 2022-04-18 04:46 UTC
Labels: bug
