### ISSUE TITLE
[Bug] Mod view 7tv is not shown anymore

### ISSUE THREAD

**Issue by AndyLCQ** [SevenTV/SevenTV#251] opened 2022-04-19 19:11 UTC
**Describe the bug**
When I am on Twitch mod view, I don't see anymore the 7tv button at the bottom right and the chat 7tv emote are not shown too.

It works when I am on a normal chat.

**To Reproduce**
1. Go to https://www.twitch.tv/moderator/xxx

**Expected behavior**
See the 7tv button

**Screenshots**
https://imgur.com/a/m0zHYHT
![image](https://user-images.githubusercontent.com/9293962/164078148-a5228c2b-1e73-4380-8250-7681c52272d6.png)

**Version:**
2.2.0

**Comment by AnatoleAM** [comment] 2022-04-19 19:17
Duplicate of #244

**Closed by AnatoleAM** 2022-04-19 19:17 UTC
Labels: bug

**Comment by AndyLCQ** [comment] 2022-04-19 19:22
Oh thanks sorry I just watch opened issue.
