### ISSUE TITLE
7tv emotes not showing with FFZ enabled on certain channel

### ISSUE THREAD

**Issue by JaRail** [SevenTV/SevenTV#265] opened 2022-05-24 18:13 UTC
One of the channels I mod (Deku) has a conflict where if FFZ is enabled, 7tv emotes do not show up. Viewers report that 7tv emotes work fine for them in other twitch channels. I've verified for myself that I also see 7tv emotes working properly in other channels. I'm not sure what makes our channel unique. I'm not aware of us being in any twitch experiments (eg chants) at the moment. In Deku's channel, we use Twitch (static and animated), BTTV, FFZ, and 7tv emotes. We use both public shared and unique uploaded BTTV emotes. I've tried both mod&subbed + unmodded&unsubbed accounts. Tried both FFZ supporter and non-supporter accounts.

**To Reproduce**
1. Enable 7tv and FFZ
2. Visit https://www.twitch.tv/popout/deku/chat
3. Attempt to use a 7tv emote

**Expected behavior**
Emote displays in chat

**Screenshots**
FFZ enabled:
![ffz enabled](https://user-images.githubusercontent.com/8772225/170103474-6b78dd15-afde-424d-bfe6-ae928ff82d48.png)

FFZ disabled:
![ffz disabled](https://user-images.githubusercontent.com/8772225/170103499-925a2ec7-4702-4886-9505-fa1b2a58f105.png)

**Version:**
Reproducible in both Chrome and Firefox.
7tv 2.2.2
ffz 1.57 (chrome), ffz 4.0 (firefox)

**Comment by Excellify** [comment] 2022-05-25 20:12
This is most likely caused by a desync of the username that is stored on 7tv and the current one on twitch. I assume the stream recently changed his name on twitch. The issue should mostly be fixed by #264, but some issues might remain such as instant emotes updates. Getting the streamer to log out and back in on 7tv.app will most likely fix the issue immediately.

**Closed by Excellify** 2022-05-25 20:12 UTC
Labels: bug

**Comment by JaRail** [comment] 2022-05-25 22:49
Yup, streamer recently name changed. Having the streamer log out and back in seems to have fixed the issue for everyone. Thanks for the help, you beautiful genius!
