### ISSUE TITLE
[Bug] Our own typed emote back to string after another chat massage popped

### ISSUE THREAD

**Issue by akmalabiyoga** [SevenTV/SevenTV#290] opened 2022-08-14 14:54 UTC
**Describe the bug**
Your typed emote images vanish and return to only string after another chat messages sent. You can still see another chat emote normally

**To Reproduce**
1. Type emote and enter
2. Wait until anyone (even yourself) sent another chat

**Expected behavior**
All emote including the one you typed is shown in the chat

**Screenshots**
![SS1](https://user-images.githubusercontent.com/14260647/184541999-f572ea5c-e86d-42ee-b37f-b6d796f4426f.png)
I typed emote twice 

![SS2](https://user-images.githubusercontent.com/14260647/184542008-3f158a72-1ff2-4029-a896-16e395707527.png)
when another chat appear, the emote before is gone, except the top one

![SS3](https://user-images.githubusercontent.com/14260647/184542093-e366b7c0-dd9d-4889-846a-7b01a51cc7ec.png)
all my typed emote is back to string except the top one

![SS4](https://user-images.githubusercontent.com/14260647/184542317-bae524a9-88b3-47f7-a9c7-13c0558018ce.png)
I still can see other people typed emote

**Version:**
The version where the bug is occuring 2.2.2

**Another note:**
- Tested on Microsoft Edge, Firefox, Google Chrome with only 7tv extension installed
- The problem occur only recently for me, idk if the extension on my browser only updated recently or not
- Problem not occured on Youtube chat
- I asked some other chat, some have this problem, some not
- Only on 3rd party emotes (FFZ, BTTV, 7TV)

**Comment by AnatoleAM** [comment] 2022-08-14 14:59
Duplicate of #286

**Closed by AnatoleAM** 2022-08-14 14:59 UTC
Labels: bug
