### ISSUE TITLE
[BUG] Emotes typed by user "sometimes" revert back to text

### ISSUE THREAD

**Issue by cabbagefork** [SevenTV/SevenTV#288] opened 2022-08-13 22:54 UTC
**Describe the bug**
Pretty much what the title says. Typing out an emote shows the emote for a brief second, then reverts back to text. This does not affect emotes typed by other chatters.

**To Reproduce**
This bug doesn't exactly happen every single time (no clue why)
1. Type out an emote

**Expected behavior**
It doesn't revert to text.

**Gif**
![710](https://user-images.githubusercontent.com/31359599/184515928-2f74b0a6-95d1-472c-b5c3-e4ad528828d9.gif)

**Version:**
Latest (2.2.2)

**Comment by AnatoleAM** [comment] 2022-08-13 22:57
Duplicate of #286

**Closed by AnatoleAM** 2022-08-13 22:57 UTC
Labels: bug
