### ISSUE TITLE
mentions are shown twice used alongside with bttv extension ..

### ISSUE THREAD

**Issue by FourLineCode** [SevenTV/SevenTV#37] opened 2021-05-31 08:01 UTC
i use 7tv extension along side with bttv extension because i need some of the settings bttv provides .. but mentions in chat are shown twice because of it .. i dont know if its because of bttv or not .. it might just be a 7tv extension bug

**Comment by AnatoleAM** [comment] 2021-05-31 08:01
Transferring to seventv/seventv and closing as it is duplicate of #19

**Closed** 2021-05-31 08:01 UTC
