### ISSUE TITLE
[Bug] Too many messages when user gets banned

### ISSUE THREAD

**Issue by emberfox** [SevenTV/SevenTV#157] opened 2021-09-28 19:19 UTC
**Describe the bug**
Every time someone gets banned, multiple messages appear, saying the same thing. Maybe it's once for every message the user sent recently.

**To Reproduce**
1. Go to Shroud channel
2. Wait for a ban
3. See error

**Expected behavior**
One message

**Screenshots**

<img width="243" alt="repeat" src="https://user-images.githubusercontent.com/1198179/135151573-af8c21c1-e6d9-457a-ac18-e8444da8e0e4.PNG">

**Version:**
The version where the bug is occuring is 2.0 on firefox

**Comment by Excellify** [comment] 2021-09-28 19:32
Can't replicate the issue. Any other extentions you have installed that might interfere?

**Comment by emberfox** [comment] 2021-09-28 20:08
> 
> 
> Can't reproduce the issue. Any other extentions you have installed that might interfere?

try "allowing to send same message twice" on setting, I only noticed it after I messed with that

> 
> 
> This is typically because bots in some channels may timeout the same user many times, leading to more messages. This could be fixed by employing the approach taken by Chatterino, where repeated timeouts are appended as "(x times)"

Each user gets a different amount of msgs, so I don't think so

**Comment by emberfox** [comment] 2021-09-28 20:17
I've already uninstalled other twitch extensions, but on firefox, I have: Zotero, AdNauseam, Honey, Transmitter, BitWarden, DuckDuckGo Privacy Essentials, Facebook Container and Chrome Remote Desktop. I don't think they would be an issue

**Comment by AnatoleAM** [comment] 2021-09-28 20:19
This is an issue native to the extension, which as I said is primarily because Twich can send more than a single timeout message. Although it's not impossible there's also a problem with code being duplicated, I'll have a look at this

**Comment by KetJex** [comment] 2021-11-20 22:19
Happening to me as well. Using FrankerFacez and 7TV, no BTTV.
![image](https://user-images.githubusercontent.com/31283318/142742407-43a33024-f0a7-4dce-85bc-5060482826c5.png)
I'm pretty certain the timeout isn't actually being issued this many times from a bot. Scrolling up and down seems to duplicate the message more, but it could just be because there's more messages coming in as I'm scrolling.

**Comment by AnatoleAM** [comment] 2022-04-15 22:43
Confirmed fixed in 2.2.0

**Closed by AnatoleAM** 2022-04-15 22:43 UTC
Labels: bug
